//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 03:42:01 PM CEST 
//


package org.apache.nutch.indexer.domjsoup.rule;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.nutch.indexer.domjsoup.rule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.nutch.indexer.domjsoup.rule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parse.Fields.TextProcess.Append }
     * 
     */
    public Parse.Fields.TextProcess.Append createParseFieldsTextProcessAppend() {
        return new Parse.Fields.TextProcess.Append();
    }

    /**
     * Create an instance of {@link Parse.Fields.TextProcess.Split }
     * 
     */
    public Parse.Fields.TextProcess.Split createParseFieldsTextProcessSplit() {
        return new Parse.Fields.TextProcess.Split();
    }

    /**
     * Create an instance of {@link Parse.Fields.Elastic }
     * 
     */
    public Parse.Fields.Elastic createParseFieldsElastic() {
        return new Parse.Fields.Elastic();
    }

    /**
     * Create an instance of {@link Parse.Fields.TextProcess.Trim }
     * 
     */
    public Parse.Fields.TextProcess.Trim createParseFieldsTextProcessTrim() {
        return new Parse.Fields.TextProcess.Trim();
    }

    /**
     * Create an instance of {@link Parse.Fields }
     * 
     */
    public Parse.Fields createParseFields() {
        return new Parse.Fields();
    }

    /**
     * Create an instance of {@link Parse.Fields.TextProcess.Substring }
     * 
     */
    public Parse.Fields.TextProcess.Substring createParseFieldsTextProcessSubstring() {
        return new Parse.Fields.TextProcess.Substring();
    }

    /**
     * Create an instance of {@link Parse.Fields.TextProcess }
     * 
     */
    public Parse.Fields.TextProcess createParseFieldsTextProcess() {
        return new Parse.Fields.TextProcess();
    }

    /**
     * Create an instance of {@link Parse.Fields.TextProcess.Replace }
     * 
     */
    public Parse.Fields.TextProcess.Replace createParseFieldsTextProcessReplace() {
        return new Parse.Fields.TextProcess.Replace();
    }

    /**
     * Create an instance of {@link Parse }
     * 
     */
    public Parse createParse() {
        return new Parse();
    }

}
