//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 11:36:30 AM CEST 
//


package org.apache.nutch.indexer.domjsoup.rule;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fields" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="textProcessAlternativeCheck" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="enable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="containsVal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="referenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="processingUrl" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="nothingFoundAction">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="setcustomVal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="customVal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="moveToParent">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="goBackParentsNumbers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="isMultiple" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="equalcheckBeforeTextProcess" type="{}equalcheck"/>
 *                   &lt;element name="elastic">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="elasticprocesstype">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="processFieldJsoup"/>
 *                                   &lt;enumeration value="setFieldValue"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="returnType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="text"/>
 *                         &lt;enumeration value="html"/>
 *                         &lt;enumeration value="attr"/>
 *                         &lt;enumeration value="count"/>
 *                         &lt;enumeration value="static"/>
 *                         &lt;enumeration value="joinfields"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="attrname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="staticval" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="multipleSeparator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="joinfields">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="textProcess" type="{}textP"/>
 *                   &lt;element name="textProcessAlternative" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="textProcess" type="{}textP"/>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="equalcheckAfterTextProcess" type="{}equalcheck"/>
 *                   &lt;element name="convertToType">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dateFormatToCheck" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="dateConvertToFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="defaultDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="type">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="none"/>
 *                                   &lt;enumeration value="empty"/>
 *                                   &lt;enumeration value="integer"/>
 *                                   &lt;enumeration value="float"/>
 *                                   &lt;enumeration value="date"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fields"
})
@XmlRootElement(name = "parse")
public class Parse {

    @XmlElement(required = true)
    protected List<Parse.Fields> fields;

    /**
     * Gets the value of the fields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parse.Fields }
     * 
     * 
     */
    public List<Parse.Fields> getFields() {
        if (fields == null) {
            fields = new ArrayList<Parse.Fields>();
        }
        return this.fields;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="textProcessAlternativeCheck" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="enable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="containsVal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="referenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="processingUrl" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="nothingFoundAction">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="setcustomVal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="customVal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="moveToParent">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="goBackParentsNumbers" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="isMultiple" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="equalcheckBeforeTextProcess" type="{}equalcheck"/>
     *         &lt;element name="elastic">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="elasticprocesstype">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="processFieldJsoup"/>
     *                         &lt;enumeration value="setFieldValue"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="returnType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="text"/>
     *               &lt;enumeration value="html"/>
     *               &lt;enumeration value="attr"/>
     *               &lt;enumeration value="count"/>
     *               &lt;enumeration value="static"/>
     *               &lt;enumeration value="joinfields"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="attrname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="staticval" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="multipleSeparator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="joinfields">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="textProcess" type="{}textP"/>
     *         &lt;element name="textProcessAlternative" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="textProcess" type="{}textP"/>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="equalcheckAfterTextProcess" type="{}equalcheck"/>
     *         &lt;element name="convertToType">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="dateFormatToCheck" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="dateConvertToFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="defaultDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="type">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="none"/>
     *                         &lt;enumeration value="empty"/>
     *                         &lt;enumeration value="integer"/>
     *                         &lt;enumeration value="float"/>
     *                         &lt;enumeration value="date"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldname",
        "jsoupquery",
        "textProcessAlternativeCheck",
        "processingUrl",
        "nothingFoundAction",
        "moveToParent",
        "isMultiple",
        "equalcheckBeforeTextProcess",
        "elastic",
        "returnType",
        "attrname",
        "staticval",
        "multipleSeparator",
        "joinfields",
        "textProcess",
        "textProcessAlternative",
        "equalcheckAfterTextProcess",
        "convertToType"
    })
    public static class Fields {

        @XmlElement(required = true)
        protected String fieldname;
        @XmlElement(required = true)
        protected String jsoupquery;
        @XmlElement(required = true)
        protected List<Parse.Fields.TextProcessAlternativeCheck> textProcessAlternativeCheck;
        @XmlElement(defaultValue = "false")
        protected boolean processingUrl;
        @XmlElement(required = true)
        protected Parse.Fields.NothingFoundAction nothingFoundAction;
        @XmlElement(required = true)
        protected Parse.Fields.MoveToParent moveToParent;
        @XmlElement(defaultValue = "false")
        protected boolean isMultiple;
        @XmlElement(required = true)
        protected Equalcheck equalcheckBeforeTextProcess;
        @XmlElement(required = true)
        protected Parse.Fields.Elastic elastic;
        @XmlElement(required = true)
        protected String returnType;
        @XmlElement(required = true)
        protected String attrname;
        @XmlElement(required = true)
        protected String staticval;
        @XmlElement(required = true, defaultValue = "|")
        protected String multipleSeparator;
        @XmlElement(required = true)
        protected Parse.Fields.Joinfields joinfields;
        @XmlElement(required = true)
        protected TextP textProcess;
        @XmlElement(required = true)
        protected List<Parse.Fields.TextProcessAlternative> textProcessAlternative;
        @XmlElement(required = true)
        protected Equalcheck equalcheckAfterTextProcess;
        @XmlElement(required = true)
        protected Parse.Fields.ConvertToType convertToType;

        /**
         * Gets the value of the fieldname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFieldname() {
            return fieldname;
        }

        /**
         * Sets the value of the fieldname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFieldname(String value) {
            this.fieldname = value;
        }

        /**
         * Gets the value of the jsoupquery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJsoupquery() {
            return jsoupquery;
        }

        /**
         * Sets the value of the jsoupquery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJsoupquery(String value) {
            this.jsoupquery = value;
        }

        /**
         * Gets the value of the textProcessAlternativeCheck property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the textProcessAlternativeCheck property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTextProcessAlternativeCheck().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Parse.Fields.TextProcessAlternativeCheck }
         * 
         * 
         */
        public List<Parse.Fields.TextProcessAlternativeCheck> getTextProcessAlternativeCheck() {
            if (textProcessAlternativeCheck == null) {
                textProcessAlternativeCheck = new ArrayList<Parse.Fields.TextProcessAlternativeCheck>();
            }
            return this.textProcessAlternativeCheck;
        }

        /**
         * Gets the value of the processingUrl property.
         * 
         */
        public boolean isProcessingUrl() {
            return processingUrl;
        }

        /**
         * Sets the value of the processingUrl property.
         * 
         */
        public void setProcessingUrl(boolean value) {
            this.processingUrl = value;
        }

        /**
         * Gets the value of the nothingFoundAction property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.NothingFoundAction }
         *     
         */
        public Parse.Fields.NothingFoundAction getNothingFoundAction() {
            return nothingFoundAction;
        }

        /**
         * Sets the value of the nothingFoundAction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.NothingFoundAction }
         *     
         */
        public void setNothingFoundAction(Parse.Fields.NothingFoundAction value) {
            this.nothingFoundAction = value;
        }

        /**
         * Gets the value of the moveToParent property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.MoveToParent }
         *     
         */
        public Parse.Fields.MoveToParent getMoveToParent() {
            return moveToParent;
        }

        /**
         * Sets the value of the moveToParent property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.MoveToParent }
         *     
         */
        public void setMoveToParent(Parse.Fields.MoveToParent value) {
            this.moveToParent = value;
        }

        /**
         * Gets the value of the isMultiple property.
         * 
         */
        public boolean isIsMultiple() {
            return isMultiple;
        }

        /**
         * Sets the value of the isMultiple property.
         * 
         */
        public void setIsMultiple(boolean value) {
            this.isMultiple = value;
        }

        /**
         * Gets the value of the equalcheckBeforeTextProcess property.
         * 
         * @return
         *     possible object is
         *     {@link Equalcheck }
         *     
         */
        public Equalcheck getEqualcheckBeforeTextProcess() {
            return equalcheckBeforeTextProcess;
        }

        /**
         * Sets the value of the equalcheckBeforeTextProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Equalcheck }
         *     
         */
        public void setEqualcheckBeforeTextProcess(Equalcheck value) {
            this.equalcheckBeforeTextProcess = value;
        }

        /**
         * Gets the value of the elastic property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.Elastic }
         *     
         */
        public Parse.Fields.Elastic getElastic() {
            return elastic;
        }

        /**
         * Sets the value of the elastic property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.Elastic }
         *     
         */
        public void setElastic(Parse.Fields.Elastic value) {
            this.elastic = value;
        }

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReturnType() {
            return returnType;
        }

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReturnType(String value) {
            this.returnType = value;
        }

        /**
         * Gets the value of the attrname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrname() {
            return attrname;
        }

        /**
         * Sets the value of the attrname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrname(String value) {
            this.attrname = value;
        }

        /**
         * Gets the value of the staticval property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStaticval() {
            return staticval;
        }

        /**
         * Sets the value of the staticval property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStaticval(String value) {
            this.staticval = value;
        }

        /**
         * Gets the value of the multipleSeparator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMultipleSeparator() {
            return multipleSeparator;
        }

        /**
         * Sets the value of the multipleSeparator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMultipleSeparator(String value) {
            this.multipleSeparator = value;
        }

        /**
         * Gets the value of the joinfields property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.Joinfields }
         *     
         */
        public Parse.Fields.Joinfields getJoinfields() {
            return joinfields;
        }

        /**
         * Sets the value of the joinfields property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.Joinfields }
         *     
         */
        public void setJoinfields(Parse.Fields.Joinfields value) {
            this.joinfields = value;
        }

        /**
         * Gets the value of the textProcess property.
         * 
         * @return
         *     possible object is
         *     {@link TextP }
         *     
         */
        public TextP getTextProcess() {
            return textProcess;
        }

        /**
         * Sets the value of the textProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextP }
         *     
         */
        public void setTextProcess(TextP value) {
            this.textProcess = value;
        }

        /**
         * Gets the value of the textProcessAlternative property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the textProcessAlternative property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTextProcessAlternative().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Parse.Fields.TextProcessAlternative }
         * 
         * 
         */
        public List<Parse.Fields.TextProcessAlternative> getTextProcessAlternative() {
            if (textProcessAlternative == null) {
                textProcessAlternative = new ArrayList<Parse.Fields.TextProcessAlternative>();
            }
            return this.textProcessAlternative;
        }

        /**
         * Gets the value of the equalcheckAfterTextProcess property.
         * 
         * @return
         *     possible object is
         *     {@link Equalcheck }
         *     
         */
        public Equalcheck getEqualcheckAfterTextProcess() {
            return equalcheckAfterTextProcess;
        }

        /**
         * Sets the value of the equalcheckAfterTextProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Equalcheck }
         *     
         */
        public void setEqualcheckAfterTextProcess(Equalcheck value) {
            this.equalcheckAfterTextProcess = value;
        }

        /**
         * Gets the value of the convertToType property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.ConvertToType }
         *     
         */
        public Parse.Fields.ConvertToType getConvertToType() {
            return convertToType;
        }

        /**
         * Sets the value of the convertToType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.ConvertToType }
         *     
         */
        public void setConvertToType(Parse.Fields.ConvertToType value) {
            this.convertToType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="dateFormatToCheck" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="dateConvertToFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="defaultDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="type">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="none"/>
         *               &lt;enumeration value="empty"/>
         *               &lt;enumeration value="integer"/>
         *               &lt;enumeration value="float"/>
         *               &lt;enumeration value="date"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dateFormatToCheck",
            "dateConvertToFormat",
            "defaultDate",
            "type"
        })
        public static class ConvertToType {

            @XmlElement(required = true)
            protected String dateFormatToCheck;
            @XmlElement(required = true)
            protected String dateConvertToFormat;
            @XmlElement(required = true)
            protected String defaultDate;
            @XmlElement(required = true)
            protected String type;

            /**
             * Gets the value of the dateFormatToCheck property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateFormatToCheck() {
                return dateFormatToCheck;
            }

            /**
             * Sets the value of the dateFormatToCheck property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateFormatToCheck(String value) {
                this.dateFormatToCheck = value;
            }

            /**
             * Gets the value of the dateConvertToFormat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateConvertToFormat() {
                return dateConvertToFormat;
            }

            /**
             * Sets the value of the dateConvertToFormat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateConvertToFormat(String value) {
                this.dateConvertToFormat = value;
            }

            /**
             * Gets the value of the defaultDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDefaultDate() {
                return defaultDate;
            }

            /**
             * Sets the value of the defaultDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDefaultDate(String value) {
                this.defaultDate = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="elasticprocesstype">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="processFieldJsoup"/>
         *               &lt;enumeration value="setFieldValue"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "findintoelastic",
            "findUrlValue",
            "fieldName",
            "elasticprocesstype"
        })
        public static class Elastic {

            @XmlElement(defaultValue = "false")
            protected boolean findintoelastic;
            @XmlElement(required = true)
            protected String findUrlValue;
            @XmlElement(required = true)
            protected String fieldName;
            @XmlElement(required = true)
            protected String elasticprocesstype;

            /**
             * Gets the value of the findintoelastic property.
             * 
             */
            public boolean isFindintoelastic() {
                return findintoelastic;
            }

            /**
             * Sets the value of the findintoelastic property.
             * 
             */
            public void setFindintoelastic(boolean value) {
                this.findintoelastic = value;
            }

            /**
             * Gets the value of the findUrlValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFindUrlValue() {
                return findUrlValue;
            }

            /**
             * Sets the value of the findUrlValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFindUrlValue(String value) {
                this.findUrlValue = value;
            }

            /**
             * Gets the value of the fieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFieldName() {
                return fieldName;
            }

            /**
             * Sets the value of the fieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFieldName(String value) {
                this.fieldName = value;
            }

            /**
             * Gets the value of the elasticprocesstype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getElasticprocesstype() {
                return elasticprocesstype;
            }

            /**
             * Sets the value of the elasticprocesstype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setElasticprocesstype(String value) {
                this.elasticprocesstype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fieldName",
            "separator"
        })
        public static class Joinfields {

            @XmlElement(required = true)
            protected List<String> fieldName;
            @XmlElement(required = true)
            protected String separator;

            /**
             * Gets the value of the fieldName property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the fieldName property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFieldName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getFieldName() {
                if (fieldName == null) {
                    fieldName = new ArrayList<String>();
                }
                return this.fieldName;
            }

            /**
             * Gets the value of the separator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeparator() {
                return separator;
            }

            /**
             * Sets the value of the separator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeparator(String value) {
                this.separator = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="goBackParentsNumbers" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "enabled",
            "goBackParentsNumbers",
            "jsoupquery"
        })
        public static class MoveToParent {

            @XmlElement(defaultValue = "false")
            protected boolean enabled;
            protected int goBackParentsNumbers;
            @XmlElement(required = true)
            protected String jsoupquery;

            /**
             * Gets the value of the enabled property.
             * 
             */
            public boolean isEnabled() {
                return enabled;
            }

            /**
             * Sets the value of the enabled property.
             * 
             */
            public void setEnabled(boolean value) {
                this.enabled = value;
            }

            /**
             * Gets the value of the goBackParentsNumbers property.
             * 
             */
            public int getGoBackParentsNumbers() {
                return goBackParentsNumbers;
            }

            /**
             * Sets the value of the goBackParentsNumbers property.
             * 
             */
            public void setGoBackParentsNumbers(int value) {
                this.goBackParentsNumbers = value;
            }

            /**
             * Gets the value of the jsoupquery property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJsoupquery() {
                return jsoupquery;
            }

            /**
             * Sets the value of the jsoupquery property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJsoupquery(String value) {
                this.jsoupquery = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="setcustomVal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="customVal" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "setcustomVal",
            "customVal"
        })
        public static class NothingFoundAction {

            protected boolean setcustomVal;
            @XmlElement(required = true)
            protected String customVal;

            /**
             * Gets the value of the setcustomVal property.
             * 
             */
            public boolean isSetcustomVal() {
                return setcustomVal;
            }

            /**
             * Sets the value of the setcustomVal property.
             * 
             */
            public void setSetcustomVal(boolean value) {
                this.setcustomVal = value;
            }

            /**
             * Gets the value of the customVal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomVal() {
                return customVal;
            }

            /**
             * Sets the value of the customVal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomVal(String value) {
                this.customVal = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="textProcess" type="{}textP"/>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "textProcess",
            "id"
        })
        public static class TextProcessAlternative {

            @XmlElement(required = true)
            protected TextP textProcess;
            @XmlElement(required = true)
            protected String id;

            /**
             * Gets the value of the textProcess property.
             * 
             * @return
             *     possible object is
             *     {@link TextP }
             *     
             */
            public TextP getTextProcess() {
                return textProcess;
            }

            /**
             * Sets the value of the textProcess property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextP }
             *     
             */
            public void setTextProcess(TextP value) {
                this.textProcess = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="enable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="containsVal" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="referenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "enable",
            "containsVal",
            "referenceId"
        })
        public static class TextProcessAlternativeCheck {

            @XmlElement(defaultValue = "false")
            protected boolean enable;
            @XmlElement(required = true)
            protected String containsVal;
            @XmlElement(required = true)
            protected String referenceId;

            /**
             * Gets the value of the enable property.
             * 
             */
            public boolean isEnable() {
                return enable;
            }

            /**
             * Sets the value of the enable property.
             * 
             */
            public void setEnable(boolean value) {
                this.enable = value;
            }

            /**
             * Gets the value of the containsVal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContainsVal() {
                return containsVal;
            }

            /**
             * Sets the value of the containsVal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContainsVal(String value) {
                this.containsVal = value;
            }

            /**
             * Gets the value of the referenceId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReferenceId() {
                return referenceId;
            }

            /**
             * Sets the value of the referenceId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReferenceId(String value) {
                this.referenceId = value;
            }

        }

    }

}
