//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 09:58:34 AM CEST 
//


package org.apache.nutch.indexer.domjsoup.rule;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fields" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="equalcheckBeforeTextProcess" type="{}equalcheck"/>
 *                   &lt;element name="elastic">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="elasticprocesstype">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="processFieldJsoup"/>
 *                                   &lt;enumeration value="setFieldValue"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="returnType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="text"/>
 *                         &lt;enumeration value="html"/>
 *                         &lt;enumeration value="attr"/>
 *                         &lt;enumeration value="count"/>
 *                         &lt;enumeration value="static"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="attrname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="staticval" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="textProcess">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="trim" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="left"/>
 *                                             &lt;enumeration value="right"/>
 *                                             &lt;enumeration value="both"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="replace" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="split">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                                       &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="append" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="before"/>
 *                                             &lt;enumeration value="after"/>
 *                                             &lt;enumeration value="both"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="substring">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="beginindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="endindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="type">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="beginindex"/>
 *                                             &lt;enumeration value="fromto"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="equalcheckAfterTextProcess" type="{}equalcheck"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fields"
})
@XmlRootElement(name = "parse")
public class Parse {

    @XmlElement(required = true)
    protected List<Parse.Fields> fields;

    /**
     * Gets the value of the fields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parse.Fields }
     * 
     * 
     */
    public List<Parse.Fields> getFields() {
        if (fields == null) {
            fields = new ArrayList<Parse.Fields>();
        }
        return this.fields;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="equalcheckBeforeTextProcess" type="{}equalcheck"/>
     *         &lt;element name="elastic">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="elasticprocesstype">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="processFieldJsoup"/>
     *                         &lt;enumeration value="setFieldValue"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="returnType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="text"/>
     *               &lt;enumeration value="html"/>
     *               &lt;enumeration value="attr"/>
     *               &lt;enumeration value="count"/>
     *               &lt;enumeration value="static"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="attrname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="staticval" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="textProcess">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="trim" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="left"/>
     *                                   &lt;enumeration value="right"/>
     *                                   &lt;enumeration value="both"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="replace" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="split">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *                             &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="append" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="before"/>
     *                                   &lt;enumeration value="after"/>
     *                                   &lt;enumeration value="both"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="substring">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="beginindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="endindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="type">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="beginindex"/>
     *                                   &lt;enumeration value="fromto"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="equalcheckAfterTextProcess" type="{}equalcheck"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldname",
        "jsoupquery",
        "equalcheckBeforeTextProcess",
        "elastic",
        "returnType",
        "attrname",
        "staticval",
        "textProcess",
        "equalcheckAfterTextProcess"
    })
    public static class Fields {

        @XmlElement(required = true)
        protected String fieldname;
        @XmlElement(required = true)
        protected String jsoupquery;
        @XmlElement(required = true)
        protected Equalcheck equalcheckBeforeTextProcess;
        @XmlElement(required = true)
        protected Parse.Fields.Elastic elastic;
        @XmlElement(required = true)
        protected String returnType;
        @XmlElement(required = true)
        protected String attrname;
        @XmlElement(required = true)
        protected String staticval;
        @XmlElement(required = true)
        protected Parse.Fields.TextProcess textProcess;
        @XmlElement(required = true)
        protected Equalcheck equalcheckAfterTextProcess;

        /**
         * Gets the value of the fieldname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFieldname() {
            return fieldname;
        }

        /**
         * Sets the value of the fieldname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFieldname(String value) {
            this.fieldname = value;
        }

        /**
         * Gets the value of the jsoupquery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJsoupquery() {
            return jsoupquery;
        }

        /**
         * Sets the value of the jsoupquery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJsoupquery(String value) {
            this.jsoupquery = value;
        }

        /**
         * Gets the value of the equalcheckBeforeTextProcess property.
         * 
         * @return
         *     possible object is
         *     {@link Equalcheck }
         *     
         */
        public Equalcheck getEqualcheckBeforeTextProcess() {
            return equalcheckBeforeTextProcess;
        }

        /**
         * Sets the value of the equalcheckBeforeTextProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Equalcheck }
         *     
         */
        public void setEqualcheckBeforeTextProcess(Equalcheck value) {
            this.equalcheckBeforeTextProcess = value;
        }

        /**
         * Gets the value of the elastic property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.Elastic }
         *     
         */
        public Parse.Fields.Elastic getElastic() {
            return elastic;
        }

        /**
         * Sets the value of the elastic property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.Elastic }
         *     
         */
        public void setElastic(Parse.Fields.Elastic value) {
            this.elastic = value;
        }

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReturnType() {
            return returnType;
        }

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReturnType(String value) {
            this.returnType = value;
        }

        /**
         * Gets the value of the attrname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrname() {
            return attrname;
        }

        /**
         * Sets the value of the attrname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrname(String value) {
            this.attrname = value;
        }

        /**
         * Gets the value of the staticval property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStaticval() {
            return staticval;
        }

        /**
         * Sets the value of the staticval property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStaticval(String value) {
            this.staticval = value;
        }

        /**
         * Gets the value of the textProcess property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.TextProcess }
         *     
         */
        public Parse.Fields.TextProcess getTextProcess() {
            return textProcess;
        }

        /**
         * Sets the value of the textProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.TextProcess }
         *     
         */
        public void setTextProcess(Parse.Fields.TextProcess value) {
            this.textProcess = value;
        }

        /**
         * Gets the value of the equalcheckAfterTextProcess property.
         * 
         * @return
         *     possible object is
         *     {@link Equalcheck }
         *     
         */
        public Equalcheck getEqualcheckAfterTextProcess() {
            return equalcheckAfterTextProcess;
        }

        /**
         * Sets the value of the equalcheckAfterTextProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Equalcheck }
         *     
         */
        public void setEqualcheckAfterTextProcess(Equalcheck value) {
            this.equalcheckAfterTextProcess = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="elasticprocesstype">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="processFieldJsoup"/>
         *               &lt;enumeration value="setFieldValue"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "findintoelastic",
            "findUrlValue",
            "fieldName",
            "elasticprocesstype"
        })
        public static class Elastic {

            @XmlElement(defaultValue = "false")
            protected boolean findintoelastic;
            @XmlElement(required = true)
            protected String findUrlValue;
            @XmlElement(required = true)
            protected String fieldName;
            @XmlElement(required = true)
            protected String elasticprocesstype;

            /**
             * Gets the value of the findintoelastic property.
             * 
             */
            public boolean isFindintoelastic() {
                return findintoelastic;
            }

            /**
             * Sets the value of the findintoelastic property.
             * 
             */
            public void setFindintoelastic(boolean value) {
                this.findintoelastic = value;
            }

            /**
             * Gets the value of the findUrlValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFindUrlValue() {
                return findUrlValue;
            }

            /**
             * Sets the value of the findUrlValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFindUrlValue(String value) {
                this.findUrlValue = value;
            }

            /**
             * Gets the value of the fieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFieldName() {
                return fieldName;
            }

            /**
             * Sets the value of the fieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFieldName(String value) {
                this.fieldName = value;
            }

            /**
             * Gets the value of the elasticprocesstype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getElasticprocesstype() {
                return elasticprocesstype;
            }

            /**
             * Sets the value of the elasticprocesstype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setElasticprocesstype(String value) {
                this.elasticprocesstype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="trim" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="left"/>
         *                         &lt;enumeration value="right"/>
         *                         &lt;enumeration value="both"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="replace" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="split">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
         *                   &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="append" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="before"/>
         *                         &lt;enumeration value="after"/>
         *                         &lt;enumeration value="both"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="substring">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="beginindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="endindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="type">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="beginindex"/>
         *                         &lt;enumeration value="fromto"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trim",
            "replace",
            "split",
            "append",
            "substring",
            "regex"
        })
        public static class TextProcess {

            @XmlElement(required = true)
            protected List<Parse.Fields.TextProcess.Trim> trim;
            @XmlElement(required = true)
            protected List<Parse.Fields.TextProcess.Replace> replace;
            @XmlElement(required = true)
            protected Parse.Fields.TextProcess.Split split;
            @XmlElement(required = true)
            protected List<Parse.Fields.TextProcess.Append> append;
            @XmlElement(required = true)
            protected Parse.Fields.TextProcess.Substring substring;
            @XmlElement(required = true)
            protected String regex;

            /**
             * Gets the value of the trim property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the trim property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTrim().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parse.Fields.TextProcess.Trim }
             * 
             * 
             */
            public List<Parse.Fields.TextProcess.Trim> getTrim() {
                if (trim == null) {
                    trim = new ArrayList<Parse.Fields.TextProcess.Trim>();
                }
                return this.trim;
            }

            /**
             * Gets the value of the replace property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the replace property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getReplace().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parse.Fields.TextProcess.Replace }
             * 
             * 
             */
            public List<Parse.Fields.TextProcess.Replace> getReplace() {
                if (replace == null) {
                    replace = new ArrayList<Parse.Fields.TextProcess.Replace>();
                }
                return this.replace;
            }

            /**
             * Gets the value of the split property.
             * 
             * @return
             *     possible object is
             *     {@link Parse.Fields.TextProcess.Split }
             *     
             */
            public Parse.Fields.TextProcess.Split getSplit() {
                return split;
            }

            /**
             * Sets the value of the split property.
             * 
             * @param value
             *     allowed object is
             *     {@link Parse.Fields.TextProcess.Split }
             *     
             */
            public void setSplit(Parse.Fields.TextProcess.Split value) {
                this.split = value;
            }

            /**
             * Gets the value of the append property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the append property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAppend().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parse.Fields.TextProcess.Append }
             * 
             * 
             */
            public List<Parse.Fields.TextProcess.Append> getAppend() {
                if (append == null) {
                    append = new ArrayList<Parse.Fields.TextProcess.Append>();
                }
                return this.append;
            }

            /**
             * Gets the value of the substring property.
             * 
             * @return
             *     possible object is
             *     {@link Parse.Fields.TextProcess.Substring }
             *     
             */
            public Parse.Fields.TextProcess.Substring getSubstring() {
                return substring;
            }

            /**
             * Sets the value of the substring property.
             * 
             * @param value
             *     allowed object is
             *     {@link Parse.Fields.TextProcess.Substring }
             *     
             */
            public void setSubstring(Parse.Fields.TextProcess.Substring value) {
                this.substring = value;
            }

            /**
             * Gets the value of the regex property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegex() {
                return regex;
            }

            /**
             * Sets the value of the regex property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegex(String value) {
                this.regex = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="before"/>
             *               &lt;enumeration value="after"/>
             *               &lt;enumeration value="both"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "val",
                "type"
            })
            public static class Append {

                @XmlElement(required = true)
                protected String val;
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the val property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVal() {
                    return val;
                }

                /**
                 * Sets the value of the val property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVal(String value) {
                    this.val = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "findstring",
                "val"
            })
            public static class Replace {

                @XmlElement(required = true)
                protected String findstring;
                @XmlElement(required = true)
                protected String val;

                /**
                 * Gets the value of the findstring property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindstring() {
                    return findstring;
                }

                /**
                 * Sets the value of the findstring property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindstring(String value) {
                    this.findstring = value;
                }

                /**
                 * Gets the value of the val property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVal() {
                    return val;
                }

                /**
                 * Sets the value of the val property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVal(String value) {
                    this.val = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
             *         &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "splitvalue",
                "returnindex",
                "separator"
            })
            public static class Split {

                @XmlElement(required = true)
                protected String splitvalue;
                @XmlElement(type = Integer.class)
                protected List<Integer> returnindex;
                @XmlElement(required = true)
                protected String separator;

                /**
                 * Gets the value of the splitvalue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSplitvalue() {
                    return splitvalue;
                }

                /**
                 * Sets the value of the splitvalue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSplitvalue(String value) {
                    this.splitvalue = value;
                }

                /**
                 * Gets the value of the returnindex property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the returnindex property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getReturnindex().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Integer }
                 * 
                 * 
                 */
                public List<Integer> getReturnindex() {
                    if (returnindex == null) {
                        returnindex = new ArrayList<Integer>();
                    }
                    return this.returnindex;
                }

                /**
                 * Gets the value of the separator property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSeparator() {
                    return separator;
                }

                /**
                 * Sets the value of the separator property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSeparator(String value) {
                    this.separator = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="beginindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="endindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="type">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="beginindex"/>
             *               &lt;enumeration value="fromto"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "beginindex",
                "endindex",
                "type"
            })
            public static class Substring {

                protected int beginindex;
                protected int endindex;
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the beginindex property.
                 * 
                 */
                public int getBeginindex() {
                    return beginindex;
                }

                /**
                 * Sets the value of the beginindex property.
                 * 
                 */
                public void setBeginindex(int value) {
                    this.beginindex = value;
                }

                /**
                 * Gets the value of the endindex property.
                 * 
                 */
                public int getEndindex() {
                    return endindex;
                }

                /**
                 * Sets the value of the endindex property.
                 * 
                 */
                public void setEndindex(int value) {
                    this.endindex = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="left"/>
             *               &lt;enumeration value="right"/>
             *               &lt;enumeration value="both"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "trimvalue",
                "type"
            })
            public static class Trim {

                @XmlElement(required = true)
                protected String trimvalue;
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the trimvalue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTrimvalue() {
                    return trimvalue;
                }

                /**
                 * Sets the value of the trimvalue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTrimvalue(String value) {
                    this.trimvalue = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }

        }

    }

}
