//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.01 at 02:20:46 PM CEST 
//


package org.apache.nutch.indexer.domjsoup.rule;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fields" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="elastic">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="elasticprocesstype">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="processFieldJsoup"/>
 *                                   &lt;enumeration value="setFieldValue"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="returnType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="text"/>
 *                         &lt;enumeration value="html"/>
 *                         &lt;enumeration value="attr"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="attrname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="textProcess">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="trim" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="left"/>
 *                                             &lt;enumeration value="right"/>
 *                                             &lt;enumeration value="both"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="replace" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="split" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fields"
})
@XmlRootElement(name = "parse")
public class Parse {

    @XmlElement(required = true)
    protected List<Parse.Fields> fields;

    /**
     * Gets the value of the fields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parse.Fields }
     * 
     * 
     */
    public List<Parse.Fields> getFields() {
        if (fields == null) {
            fields = new ArrayList<Parse.Fields>();
        }
        return this.fields;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fieldname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="jsoupquery" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="elastic">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="elasticprocesstype">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="processFieldJsoup"/>
     *                         &lt;enumeration value="setFieldValue"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="returnType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="text"/>
     *               &lt;enumeration value="html"/>
     *               &lt;enumeration value="attr"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="attrname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="textProcess">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="trim" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="left"/>
     *                                   &lt;enumeration value="right"/>
     *                                   &lt;enumeration value="both"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="replace" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="split" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldname",
        "jsoupquery",
        "elastic",
        "returnType",
        "attrname",
        "textProcess"
    })
    public static class Fields {

        @XmlElement(required = true)
        protected String fieldname;
        @XmlElement(required = true)
        protected String jsoupquery;
        @XmlElement(required = true)
        protected Parse.Fields.Elastic elastic;
        @XmlElement(required = true)
        protected String returnType;
        @XmlElement(required = true)
        protected String attrname;
        @XmlElement(required = true)
        protected Parse.Fields.TextProcess textProcess;

        /**
         * Gets the value of the fieldname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFieldname() {
            return fieldname;
        }

        /**
         * Sets the value of the fieldname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFieldname(String value) {
            this.fieldname = value;
        }

        /**
         * Gets the value of the jsoupquery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJsoupquery() {
            return jsoupquery;
        }

        /**
         * Sets the value of the jsoupquery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJsoupquery(String value) {
            this.jsoupquery = value;
        }

        /**
         * Gets the value of the elastic property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.Elastic }
         *     
         */
        public Parse.Fields.Elastic getElastic() {
            return elastic;
        }

        /**
         * Sets the value of the elastic property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.Elastic }
         *     
         */
        public void setElastic(Parse.Fields.Elastic value) {
            this.elastic = value;
        }

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReturnType() {
            return returnType;
        }

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReturnType(String value) {
            this.returnType = value;
        }

        /**
         * Gets the value of the attrname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrname() {
            return attrname;
        }

        /**
         * Sets the value of the attrname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrname(String value) {
            this.attrname = value;
        }

        /**
         * Gets the value of the textProcess property.
         * 
         * @return
         *     possible object is
         *     {@link Parse.Fields.TextProcess }
         *     
         */
        public Parse.Fields.TextProcess getTextProcess() {
            return textProcess;
        }

        /**
         * Sets the value of the textProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parse.Fields.TextProcess }
         *     
         */
        public void setTextProcess(Parse.Fields.TextProcess value) {
            this.textProcess = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="findintoelastic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="findUrlValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="elasticprocesstype">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="processFieldJsoup"/>
         *               &lt;enumeration value="setFieldValue"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "findintoelastic",
            "findUrlValue",
            "fieldName",
            "elasticprocesstype"
        })
        public static class Elastic {

            @XmlElement(defaultValue = "false")
            protected boolean findintoelastic;
            @XmlElement(required = true)
            protected String findUrlValue;
            @XmlElement(required = true)
            protected String fieldName;
            @XmlElement(required = true)
            protected String elasticprocesstype;

            /**
             * Gets the value of the findintoelastic property.
             * 
             */
            public boolean isFindintoelastic() {
                return findintoelastic;
            }

            /**
             * Sets the value of the findintoelastic property.
             * 
             */
            public void setFindintoelastic(boolean value) {
                this.findintoelastic = value;
            }

            /**
             * Gets the value of the findUrlValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFindUrlValue() {
                return findUrlValue;
            }

            /**
             * Sets the value of the findUrlValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFindUrlValue(String value) {
                this.findUrlValue = value;
            }

            /**
             * Gets the value of the fieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFieldName() {
                return fieldName;
            }

            /**
             * Sets the value of the fieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFieldName(String value) {
                this.fieldName = value;
            }

            /**
             * Gets the value of the elasticprocesstype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getElasticprocesstype() {
                return elasticprocesstype;
            }

            /**
             * Sets the value of the elasticprocesstype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setElasticprocesstype(String value) {
                this.elasticprocesstype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="trim" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="left"/>
         *                         &lt;enumeration value="right"/>
         *                         &lt;enumeration value="both"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="replace" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="split" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trim",
            "replace",
            "split"
        })
        public static class TextProcess {

            @XmlElement(required = true)
            protected List<Parse.Fields.TextProcess.Trim> trim;
            @XmlElement(required = true)
            protected List<Parse.Fields.TextProcess.Replace> replace;
            @XmlElement(required = true)
            protected List<Parse.Fields.TextProcess.Split> split;

            /**
             * Gets the value of the trim property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the trim property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTrim().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parse.Fields.TextProcess.Trim }
             * 
             * 
             */
            public List<Parse.Fields.TextProcess.Trim> getTrim() {
                if (trim == null) {
                    trim = new ArrayList<Parse.Fields.TextProcess.Trim>();
                }
                return this.trim;
            }

            /**
             * Gets the value of the replace property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the replace property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getReplace().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parse.Fields.TextProcess.Replace }
             * 
             * 
             */
            public List<Parse.Fields.TextProcess.Replace> getReplace() {
                if (replace == null) {
                    replace = new ArrayList<Parse.Fields.TextProcess.Replace>();
                }
                return this.replace;
            }

            /**
             * Gets the value of the split property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the split property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSplit().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parse.Fields.TextProcess.Split }
             * 
             * 
             */
            public List<Parse.Fields.TextProcess.Split> getSplit() {
                if (split == null) {
                    split = new ArrayList<Parse.Fields.TextProcess.Split>();
                }
                return this.split;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "findstring",
                "val"
            })
            public static class Replace {

                @XmlElement(required = true)
                protected String findstring;
                @XmlElement(required = true)
                protected String val;

                /**
                 * Gets the value of the findstring property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindstring() {
                    return findstring;
                }

                /**
                 * Sets the value of the findstring property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindstring(String value) {
                    this.findstring = value;
                }

                /**
                 * Gets the value of the val property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVal() {
                    return val;
                }

                /**
                 * Sets the value of the val property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVal(String value) {
                    this.val = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "splitvalue",
                "returnindex"
            })
            public static class Split {

                @XmlElement(required = true)
                protected String splitvalue;
                protected int returnindex;

                /**
                 * Gets the value of the splitvalue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSplitvalue() {
                    return splitvalue;
                }

                /**
                 * Sets the value of the splitvalue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSplitvalue(String value) {
                    this.splitvalue = value;
                }

                /**
                 * Gets the value of the returnindex property.
                 * 
                 */
                public int getReturnindex() {
                    return returnindex;
                }

                /**
                 * Sets the value of the returnindex property.
                 * 
                 */
                public void setReturnindex(int value) {
                    this.returnindex = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="left"/>
             *               &lt;enumeration value="right"/>
             *               &lt;enumeration value="both"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "trimvalue",
                "type"
            })
            public static class Trim {

                @XmlElement(required = true)
                protected String trimvalue;
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the trimvalue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTrimvalue() {
                    return trimvalue;
                }

                /**
                 * Sets the value of the trimvalue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTrimvalue(String value) {
                    this.trimvalue = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }

        }

    }

}
