//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 11:57:57 AM CEST 
//


package org.apache.nutch.indexer.domjsoup.rule;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for textP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="textP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trim" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="left"/>
 *                         &lt;enumeration value="right"/>
 *                         &lt;enumeration value="both"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="replace" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="split" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                   &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="index"/>
 *                         &lt;enumeration value="first"/>
 *                         &lt;enumeration value="last"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="append" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="before"/>
 *                         &lt;enumeration value="after"/>
 *                         &lt;enumeration value="both"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="substring">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="beginindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="endindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="beginindex"/>
 *                         &lt;enumeration value="fromto"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="percentCalculate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="appendPercentValue" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="totalValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contains">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="containValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="customValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="caseInsensitive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datePattern">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="splitPatternFromNowSubtract" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="splitPatternFromNow"/>
 *                         &lt;enumeration value="splitPattern"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="indexDef" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="dateLetter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "textP", propOrder = {
    "trim",
    "replace",
    "split",
    "append",
    "substring",
    "regex",
    "percentCalculate",
    "contains",
    "datePattern"
})
public class TextP {

    @XmlElement(required = true)
    protected List<TextP.Trim> trim;
    @XmlElement(required = true)
    protected List<TextP.Replace> replace;
    @XmlElement(required = true)
    protected List<TextP.Split> split;
    @XmlElement(required = true)
    protected List<TextP.Append> append;
    @XmlElement(required = true)
    protected TextP.Substring substring;
    @XmlElement(required = true)
    protected String regex;
    @XmlElement(required = true)
    protected TextP.PercentCalculate percentCalculate;
    @XmlElement(required = true)
    protected TextP.Contains contains;
    @XmlElement(required = true)
    protected TextP.DatePattern datePattern;

    /**
     * Gets the value of the trim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextP.Trim }
     * 
     * 
     */
    public List<TextP.Trim> getTrim() {
        if (trim == null) {
            trim = new ArrayList<TextP.Trim>();
        }
        return this.trim;
    }

    /**
     * Gets the value of the replace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the replace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReplace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextP.Replace }
     * 
     * 
     */
    public List<TextP.Replace> getReplace() {
        if (replace == null) {
            replace = new ArrayList<TextP.Replace>();
        }
        return this.replace;
    }

    /**
     * Gets the value of the split property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the split property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSplit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextP.Split }
     * 
     * 
     */
    public List<TextP.Split> getSplit() {
        if (split == null) {
            split = new ArrayList<TextP.Split>();
        }
        return this.split;
    }

    /**
     * Gets the value of the append property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the append property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppend().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextP.Append }
     * 
     * 
     */
    public List<TextP.Append> getAppend() {
        if (append == null) {
            append = new ArrayList<TextP.Append>();
        }
        return this.append;
    }

    /**
     * Gets the value of the substring property.
     * 
     * @return
     *     possible object is
     *     {@link TextP.Substring }
     *     
     */
    public TextP.Substring getSubstring() {
        return substring;
    }

    /**
     * Sets the value of the substring property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextP.Substring }
     *     
     */
    public void setSubstring(TextP.Substring value) {
        this.substring = value;
    }

    /**
     * Gets the value of the regex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegex() {
        return regex;
    }

    /**
     * Sets the value of the regex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegex(String value) {
        this.regex = value;
    }

    /**
     * Gets the value of the percentCalculate property.
     * 
     * @return
     *     possible object is
     *     {@link TextP.PercentCalculate }
     *     
     */
    public TextP.PercentCalculate getPercentCalculate() {
        return percentCalculate;
    }

    /**
     * Sets the value of the percentCalculate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextP.PercentCalculate }
     *     
     */
    public void setPercentCalculate(TextP.PercentCalculate value) {
        this.percentCalculate = value;
    }

    /**
     * Gets the value of the contains property.
     * 
     * @return
     *     possible object is
     *     {@link TextP.Contains }
     *     
     */
    public TextP.Contains getContains() {
        return contains;
    }

    /**
     * Sets the value of the contains property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextP.Contains }
     *     
     */
    public void setContains(TextP.Contains value) {
        this.contains = value;
    }

    /**
     * Gets the value of the datePattern property.
     * 
     * @return
     *     possible object is
     *     {@link TextP.DatePattern }
     *     
     */
    public TextP.DatePattern getDatePattern() {
        return datePattern;
    }

    /**
     * Sets the value of the datePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextP.DatePattern }
     *     
     */
    public void setDatePattern(TextP.DatePattern value) {
        this.datePattern = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="before"/>
     *               &lt;enumeration value="after"/>
     *               &lt;enumeration value="both"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "val",
        "type"
    })
    public static class Append {

        @XmlElement(required = true)
        protected String val;
        @XmlElement(required = true)
        protected String type;

        /**
         * Gets the value of the val property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVal() {
            return val;
        }

        /**
         * Sets the value of the val property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVal(String value) {
            this.val = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="containValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="customValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="caseInsensitive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "containValue",
        "customValue",
        "caseInsensitive"
    })
    public static class Contains {

        @XmlElement(required = true)
        protected String containValue;
        @XmlElement(required = true)
        protected String customValue;
        @XmlElement(defaultValue = "false")
        protected boolean caseInsensitive;

        /**
         * Gets the value of the containValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContainValue() {
            return containValue;
        }

        /**
         * Sets the value of the containValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContainValue(String value) {
            this.containValue = value;
        }

        /**
         * Gets the value of the customValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomValue() {
            return customValue;
        }

        /**
         * Sets the value of the customValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomValue(String value) {
            this.customValue = value;
        }

        /**
         * Gets the value of the caseInsensitive property.
         * 
         */
        public boolean isCaseInsensitive() {
            return caseInsensitive;
        }

        /**
         * Sets the value of the caseInsensitive property.
         * 
         */
        public void setCaseInsensitive(boolean value) {
            this.caseInsensitive = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="splitPatternFromNowSubtract" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="splitPatternFromNow"/>
     *               &lt;enumeration value="splitPattern"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="indexDef" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="dateLetter" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateFormat",
        "separator",
        "splitPatternFromNowSubtract",
        "type",
        "indexDef"
    })
    public static class DatePattern {

        @XmlElement(required = true, defaultValue = "M/d/y k:m:s")
        protected String dateFormat;
        @XmlElement(required = true, defaultValue = " ")
        protected String separator;
        @XmlElement(defaultValue = "false")
        protected boolean splitPatternFromNowSubtract;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected List<TextP.DatePattern.IndexDef> indexDef;

        /**
         * Gets the value of the dateFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateFormat() {
            return dateFormat;
        }

        /**
         * Sets the value of the dateFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateFormat(String value) {
            this.dateFormat = value;
        }

        /**
         * Gets the value of the separator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeparator() {
            return separator;
        }

        /**
         * Sets the value of the separator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeparator(String value) {
            this.separator = value;
        }

        /**
         * Gets the value of the splitPatternFromNowSubtract property.
         * 
         */
        public boolean isSplitPatternFromNowSubtract() {
            return splitPatternFromNowSubtract;
        }

        /**
         * Sets the value of the splitPatternFromNowSubtract property.
         * 
         */
        public void setSplitPatternFromNowSubtract(boolean value) {
            this.splitPatternFromNowSubtract = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the indexDef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the indexDef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIndexDef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextP.DatePattern.IndexDef }
         * 
         * 
         */
        public List<TextP.DatePattern.IndexDef> getIndexDef() {
            if (indexDef == null) {
                indexDef = new ArrayList<TextP.DatePattern.IndexDef>();
            }
            return this.indexDef;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="dateLetter" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "index",
            "dateLetter"
        })
        public static class IndexDef {

            protected int index;
            @XmlElement(required = true)
            protected String dateLetter;

            /**
             * Gets the value of the index property.
             * 
             */
            public int getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             */
            public void setIndex(int value) {
                this.index = value;
            }

            /**
             * Gets the value of the dateLetter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateLetter() {
                return dateLetter;
            }

            /**
             * Sets the value of the dateLetter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateLetter(String value) {
                this.dateLetter = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="appendPercentValue" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="totalValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appendPercentValue",
        "totalValue"
    })
    public static class PercentCalculate {

        protected boolean appendPercentValue;
        protected int totalValue;

        /**
         * Gets the value of the appendPercentValue property.
         * 
         */
        public boolean isAppendPercentValue() {
            return appendPercentValue;
        }

        /**
         * Sets the value of the appendPercentValue property.
         * 
         */
        public void setAppendPercentValue(boolean value) {
            this.appendPercentValue = value;
        }

        /**
         * Gets the value of the totalValue property.
         * 
         */
        public int getTotalValue() {
            return totalValue;
        }

        /**
         * Sets the value of the totalValue property.
         * 
         */
        public void setTotalValue(int value) {
            this.totalValue = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="findstring" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "findstring",
        "val"
    })
    public static class Replace {

        @XmlElement(required = true)
        protected String findstring;
        @XmlElement(required = true)
        protected String val;

        /**
         * Gets the value of the findstring property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFindstring() {
            return findstring;
        }

        /**
         * Sets the value of the findstring property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFindstring(String value) {
            this.findstring = value;
        }

        /**
         * Gets the value of the val property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVal() {
            return val;
        }

        /**
         * Sets the value of the val property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVal(String value) {
            this.val = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="splitvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="returnindex" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *         &lt;element name="separator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="index"/>
     *               &lt;enumeration value="first"/>
     *               &lt;enumeration value="last"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "splitvalue",
        "returnindex",
        "separator",
        "type"
    })
    public static class Split {

        @XmlElement(required = true)
        protected String splitvalue;
        @XmlElement(type = Integer.class)
        protected List<Integer> returnindex;
        @XmlElement(required = true)
        protected String separator;
        @XmlElement(required = true, defaultValue = "index")
        protected String type;

        /**
         * Gets the value of the splitvalue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSplitvalue() {
            return splitvalue;
        }

        /**
         * Sets the value of the splitvalue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSplitvalue(String value) {
            this.splitvalue = value;
        }

        /**
         * Gets the value of the returnindex property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the returnindex property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReturnindex().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getReturnindex() {
            if (returnindex == null) {
                returnindex = new ArrayList<Integer>();
            }
            return this.returnindex;
        }

        /**
         * Gets the value of the separator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeparator() {
            return separator;
        }

        /**
         * Sets the value of the separator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeparator(String value) {
            this.separator = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="beginindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="endindex" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="beginindex"/>
     *               &lt;enumeration value="fromto"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "beginindex",
        "endindex",
        "type"
    })
    public static class Substring {

        protected int beginindex;
        protected int endindex;
        @XmlElement(required = true)
        protected String type;

        /**
         * Gets the value of the beginindex property.
         * 
         */
        public int getBeginindex() {
            return beginindex;
        }

        /**
         * Sets the value of the beginindex property.
         * 
         */
        public void setBeginindex(int value) {
            this.beginindex = value;
        }

        /**
         * Gets the value of the endindex property.
         * 
         */
        public int getEndindex() {
            return endindex;
        }

        /**
         * Sets the value of the endindex property.
         * 
         */
        public void setEndindex(int value) {
            this.endindex = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="trimvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="left"/>
     *               &lt;enumeration value="right"/>
     *               &lt;enumeration value="both"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trimvalue",
        "type"
    })
    public static class Trim {

        @XmlElement(required = true)
        protected String trimvalue;
        @XmlElement(required = true)
        protected String type;

        /**
         * Gets the value of the trimvalue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrimvalue() {
            return trimvalue;
        }

        /**
         * Sets the value of the trimvalue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrimvalue(String value) {
            this.trimvalue = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
