//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 12:12:00 PM CEST 
//


package org.apache.nutch.indexer.domjsoup.conf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.nutch.indexer.domjsoup.conf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.nutch.indexer.domjsoup.conf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link Rules.ElasticInfo }
     * 
     */
    public Rules.ElasticInfo createRulesElasticInfo() {
        return new Rules.ElasticInfo();
    }

    /**
     * Create an instance of {@link Rules.Currencyconvert }
     * 
     */
    public Rules.Currencyconvert createRulesCurrencyconvert() {
        return new Rules.Currencyconvert();
    }

    /**
     * Create an instance of {@link Rules.Rule }
     * 
     */
    public Rules.Rule createRulesRule() {
        return new Rules.Rule();
    }

}
