//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 09:48:28 AM CEST 
//


package org.apache.nutch.indexer.domjsoup.conf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="elasticInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="clusterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hostNameOrIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="elasticPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="currencyconvert">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="csvfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="csvseparator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="startFromRow" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="colIdNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="colValueNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rule" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="urlcontain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addhtmlsourcefield" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="enablecurrencyconverter" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="currencyFieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elasticInfo",
    "currencyconvert",
    "rule"
})
@XmlRootElement(name = "rules")
public class Rules {

    @XmlElement(required = true)
    protected Rules.ElasticInfo elasticInfo;
    @XmlElement(required = true)
    protected Rules.Currencyconvert currencyconvert;
    @XmlElement(required = true)
    protected List<Rules.Rule> rule;

    /**
     * Gets the value of the elasticInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Rules.ElasticInfo }
     *     
     */
    public Rules.ElasticInfo getElasticInfo() {
        return elasticInfo;
    }

    /**
     * Sets the value of the elasticInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rules.ElasticInfo }
     *     
     */
    public void setElasticInfo(Rules.ElasticInfo value) {
        this.elasticInfo = value;
    }

    /**
     * Gets the value of the currencyconvert property.
     * 
     * @return
     *     possible object is
     *     {@link Rules.Currencyconvert }
     *     
     */
    public Rules.Currencyconvert getCurrencyconvert() {
        return currencyconvert;
    }

    /**
     * Sets the value of the currencyconvert property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rules.Currencyconvert }
     *     
     */
    public void setCurrencyconvert(Rules.Currencyconvert value) {
        this.currencyconvert = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rules.Rule }
     * 
     * 
     */
    public List<Rules.Rule> getRule() {
        if (rule == null) {
            rule = new ArrayList<Rules.Rule>();
        }
        return this.rule;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="csvfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="csvseparator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="startFromRow" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="colIdNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="colValueNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "csvfile",
        "csvseparator",
        "startFromRow",
        "colIdNumber",
        "colValueNumber"
    })
    public static class Currencyconvert {

        @XmlElement(required = true)
        protected String csvfile;
        @XmlElement(required = true)
        protected String csvseparator;
        @XmlElement(defaultValue = "0")
        protected int startFromRow;
        protected int colIdNumber;
        protected int colValueNumber;

        /**
         * Gets the value of the csvfile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCsvfile() {
            return csvfile;
        }

        /**
         * Sets the value of the csvfile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCsvfile(String value) {
            this.csvfile = value;
        }

        /**
         * Gets the value of the csvseparator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCsvseparator() {
            return csvseparator;
        }

        /**
         * Sets the value of the csvseparator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCsvseparator(String value) {
            this.csvseparator = value;
        }

        /**
         * Gets the value of the startFromRow property.
         * 
         */
        public int getStartFromRow() {
            return startFromRow;
        }

        /**
         * Sets the value of the startFromRow property.
         * 
         */
        public void setStartFromRow(int value) {
            this.startFromRow = value;
        }

        /**
         * Gets the value of the colIdNumber property.
         * 
         */
        public int getColIdNumber() {
            return colIdNumber;
        }

        /**
         * Sets the value of the colIdNumber property.
         * 
         */
        public void setColIdNumber(int value) {
            this.colIdNumber = value;
        }

        /**
         * Gets the value of the colValueNumber property.
         * 
         */
        public int getColValueNumber() {
            return colValueNumber;
        }

        /**
         * Sets the value of the colValueNumber property.
         * 
         */
        public void setColValueNumber(int value) {
            this.colValueNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="clusterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="hostNameOrIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="elasticPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clusterName",
        "hostNameOrIp",
        "elasticPort",
        "index"
    })
    public static class ElasticInfo {

        @XmlElement(required = true)
        protected String clusterName;
        @XmlElement(required = true, defaultValue = "localhost")
        protected String hostNameOrIp;
        @XmlElement(defaultValue = "9300")
        protected int elasticPort;
        @XmlElement(required = true, defaultValue = "index")
        protected String index;

        /**
         * Gets the value of the clusterName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClusterName() {
            return clusterName;
        }

        /**
         * Sets the value of the clusterName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClusterName(String value) {
            this.clusterName = value;
        }

        /**
         * Gets the value of the hostNameOrIp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHostNameOrIp() {
            return hostNameOrIp;
        }

        /**
         * Sets the value of the hostNameOrIp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHostNameOrIp(String value) {
            this.hostNameOrIp = value;
        }

        /**
         * Gets the value of the elasticPort property.
         * 
         */
        public int getElasticPort() {
            return elasticPort;
        }

        /**
         * Sets the value of the elasticPort property.
         * 
         */
        public void setElasticPort(int value) {
            this.elasticPort = value;
        }

        /**
         * Gets the value of the index property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndex() {
            return index;
        }

        /**
         * Sets the value of the index property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndex(String value) {
            this.index = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="urlcontain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addhtmlsourcefield" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="enablecurrencyconverter" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="currencyFieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "urlcontain",
        "file",
        "addhtmlsourcefield",
        "enablecurrencyconverter",
        "currencyFieldName"
    })
    public static class Rule {

        @XmlElement(required = true)
        protected String urlcontain;
        @XmlElement(required = true, defaultValue = "conf/file.xml")
        protected String file;
        @XmlElement(defaultValue = "1")
        protected boolean addhtmlsourcefield;
        @XmlElement(defaultValue = "1")
        protected boolean enablecurrencyconverter;
        @XmlElement(required = true)
        protected String currencyFieldName;

        /**
         * Gets the value of the urlcontain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrlcontain() {
            return urlcontain;
        }

        /**
         * Sets the value of the urlcontain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrlcontain(String value) {
            this.urlcontain = value;
        }

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the addhtmlsourcefield property.
         * 
         */
        public boolean isAddhtmlsourcefield() {
            return addhtmlsourcefield;
        }

        /**
         * Sets the value of the addhtmlsourcefield property.
         * 
         */
        public void setAddhtmlsourcefield(boolean value) {
            this.addhtmlsourcefield = value;
        }

        /**
         * Gets the value of the enablecurrencyconverter property.
         * 
         */
        public boolean isEnablecurrencyconverter() {
            return enablecurrencyconverter;
        }

        /**
         * Sets the value of the enablecurrencyconverter property.
         * 
         */
        public void setEnablecurrencyconverter(boolean value) {
            this.enablecurrencyconverter = value;
        }

        /**
         * Gets the value of the currencyFieldName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyFieldName() {
            return currencyFieldName;
        }

        /**
         * Sets the value of the currencyFieldName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyFieldName(String value) {
            this.currencyFieldName = value;
        }

    }

}
